services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: coolanuj042/test-next-app
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:  # This defines the network
    driver: bridge
    name: next-app-network
volumes:
  next-app-data:
    